### ISSUE TITLE
FreeSign: What should the component look like?

### ISSUE THREAD

**Issue by angelagilhotra** [kernel-community/signature-economies#21]

**Comment by andytudhope** [comment]
This is a good example: https://www.interdependence.online/declaration (scroll to bottom)

This has two aspects to it:

1. "Sign Freely" button at the bottom of the text. We can put some text above the button explaining: "If you find this essay meaningful, you may mark our shared record by sending a signed message of the whole text. This can be done freely, as there are no costs to signing onchain messages. In addition, your signature will be stored on Arweave and become a permanent part of this document's history."
2. A means of displaying all the signatures. This should likely include an avatar (optional), the ETH address or ENS name (necessary), the txID on arweave, and the timestamp (as opposed to a name and a twitter verification). It should be organised in a list, which displays the 10 most recent sigs and has a "See More" with a down arrow at the bottom to load more of them.

**Comment by Malayvasa** [comment]
Have made a new branch for freesign and added the basic UI https://github.com/kernel-community/signature-economies/commit/50a38e52887964acb05a6750080e566ad1a38e66

**Comment by angelagilhotra** [comment]
@Malayvasa can you please raise a PR?
