### ISSUE TITLE
Potential race condition on the tokenIdCounter

### ISSUE THREAD

**Issue by angelagilhotra** [kernel-community/signature-economies#26]
if 2 people try to mint at the same time, they will get the same tokenIdCounter, so the NFT id in the metadata will not match one of the two uri.

thread: https://kernel-community.slack.com/archives/C031ES44SA3/p1652864472892929

**Comment by angelagilhotra** [comment]
Approach 1: submitting tokenId along with the `url`
Approach 2: generating and storing metadata on-chain

**Comment by andytudhope** [comment]
Fixed by #30
