### ISSUE TITLE
Update the contract metadata + ascii art for mainnet

### ISSUE THREAD

**Issue by andytudhope** [kernel-community/signature-economies#34]
Note to self: we can likely do with more descriptive text due to the way this is rendered on OpenSea and places like it.

Also, just use the signature style for both contracts - it fits better in the collection image than Derrida's signature does.

https://arweave.net/dDj2ppnvu07XkfH4obgbj946KPJlYbnIUnsPnlXguZ0

Also, look into cool ascii signatures if we can find them to place in the contracts now that we can easily verify them on Etherscan once deployed.

**Comment by angelagilhotra** [comment]
this is completed right?

**Comment by andytudhope** [comment]
Yes, thanks :pray:
