### ISSUE TITLE
SoulSigns page (display all sealed NFTs + minted NFTs)

### ISSUE THREAD

**Issue by probablyangg** [kernel-community/signature-economies#55]
![sig-eco-signatures-page-bg](https://user-images.githubusercontent.com/13001517/171188593-dd5a0b7f-7bf6-4bed-a2a1-d7c5d46ef815.png)

https://api.studio.thegraph.com/query/24825/sign-eco/0.0.2/graphql

```
query MyQuery {
  signatureNFTs {
    id
    uri
    createdAtTimestamp
    steward {
      id
    }
  }
  signatureFunds {
    id
    uri
    signedAmount
    steward {
      id
    }
  }
}
```

**Comment by Malayvasa** [comment]
![SoulSign](https://user-images.githubusercontent.com/22751053/171391023-8e92d01c-137d-472e-96dc-e0133906d292.png)

I'm not sure we can fit three rows of signature nfts and have the sealed nfts visible, does this design work instead?  @andytudhope @angelagilhotra 
https://www.figma.com/file/wrr3qGMckBffSdWTgCfvr0/SoulSign?node-id=0%3A1

**Comment by andytudhope** [comment]
That is perfect, thank you @Malayvasa :pray: Let's make it happen.
